/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IVotingApp {
    function owner() external view returns (address);

    function isActive() external view returns (bool);

    function getUserBalance(address user) external view returns (uint256);

    function vote(uint256 restaurant_id, uint256 tokens) external;

    function addRestaurant(uint64 res_id, string calldata name, string calldata cuisine) external;

    function getRestaurantVotes(uint256 restaurant_id) external view returns (uint256);
}